version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app
      - /volume1:/volume1  # Mount NAS media folder vào container
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/video_production_ai
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: .
    volumes:
      - .:/app
      - /volume1:/volume1  # Mount NAS media folder vào container
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/video_production_ai
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0
    command: celery -A core worker --loglevel=info
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - api

  beat:
    build: .
    volumes:
      - .:/app
      - /volume1:/volume1  # Mount NAS media folder vào container
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/video_production_ai
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0
    command: celery -A core beat --loglevel=info
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - api
