import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()
from django.db import connection

def recreate_table():
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS video_management_reportsettings (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                schedule jsonb NOT NULL,
                one_report_per_day boolean NOT NULL,
                timezone character varying(50) NOT NULL,
                is_random boolean NOT NULL,
                random_minutes integer NOT NULL,
                updated_by character varying(255) NOT NULL
            );
        """)
        print("Table recreated successfully!")

if __name__ == "__main__":
    recreate_table()
