"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import base64
from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=(str, ''),
    ALLOWED_HOSTS=(list, []),
    LOG_LEVEL=(str, 'INFO'),
    APP_LOG_LEVEL=(str, ''),
)

# Read .env file if it exists
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '0.0.0.0'])

# ── Proxy / HTTPS settings (behind Cloudflare Tunnel) ──────────────────────
# Cloudflare Tunnel terminates SSL and forwards X-Forwarded-Proto: https
# This tells Django to trust that header so build_absolute_uri() returns https://
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
# ───────────────────────────────────────────────────────────────────────────



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    # 'drf_spectacular',
    'corsheaders',
    
    # Internal apps
    'video_management',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database — PostgreSQL only (shared with BE service: video_production)
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# DATABASE_URL must be set in .env, e.g.:
#   DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/video_production

_db_url = env('DATABASE_URL', default='')
if not _db_url:
    raise RuntimeError(
        "DATABASE_URL is not set! "
        "Add it to .env, e.g.: DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/video_production"
    )

DATABASES = {
    'default': env.db('DATABASE_URL')
}
# Optimize for multiple concurrent users by keeping DB connections open
DATABASES['default']['CONN_MAX_AGE'] = env.int('CONN_MAX_AGE', default=300)
DATABASES['default']['CONN_HEALTH_CHECKS'] = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploaded content)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging levels (tunable by env in production)
LOG_LEVEL = env('LOG_LEVEL', default='INFO').upper()
APP_LOG_LEVEL = env('APP_LOG_LEVEL', default=('DEBUG' if DEBUG else 'INFO')).upper()

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'video_management': {
            'handlers': ['console'],
            'level': APP_LOG_LEVEL,
            'propagate': False,
        },
    },
}

# REST Framework settings
JWT_SECRET = env('JWT_SECRET', default='')
JWT_BOOT_SUFFIX = env('JWT_BOOT_SUFFIX', default='')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.NestJWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] if not DEBUG else [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # Baseline guards for 50-100 concurrent users.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': env('DRF_THROTTLE_ANON', default='120/min'),
        'user': env('DRF_THROTTLE_USER', default='600/min'),
        'video_download': env('DRF_THROTTLE_VIDEO_DOWNLOAD', default='10/min'),
    },
    # Global pagination defaults for list endpoints that use DRF pagination.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': env.int('DRF_PAGE_SIZE', default=50),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'AutomationGenVideo AI API',
    'DESCRIPTION': 'Auto-generated API schema for video management and related services.',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Celery settings
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Cache: Django 4.2+ native RedisCache (dùng redis-py, không cần django-redis)
# Shared across multiple Gunicorn/Celery workers.
_redis_url = env('REDIS_URL', default=env('CELERY_BROKER_URL', default='redis://localhost:6379/0'))
try:
    import redis as _redis_lib
    _r_test = _redis_lib.from_url(_redis_url, socket_connect_timeout=1)
    _r_test.ping()
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _redis_url,
            "TIMEOUT": 300,       # 5 phút mặc định
            "KEY_PREFIX": "ai",
            "OPTIONS": {
                "socket_connect_timeout": env.float('REDIS_CONNECT_TIMEOUT', default=1.5),
                "socket_timeout": env.float('REDIS_SOCKET_TIMEOUT', default=2.0),
            },
        }
    }
except Exception:
    # Fallback khi Redis chưa chạy (dev local không có Redis)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ai-locmem",
        }
    }




# CORS settings
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=True)  # Enable for development
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://localhost:5173',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
])
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Disposition']  # cho FE đọc tên file khi tải video
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ==========================================
# RAPIDAPI CONFIGURATION
# ==========================================
RAPIDAPI_FACEBOOK_KEY = env('RAPIDAPI_FACEBOOK_KEY', default='')
RAPIDAPI_FACEBOOK_HOST = env('RAPIDAPI_FACEBOOK_HOST', default='facebook-scraper-api4.p.rapidapi.com')

# ==========================================
# TIKHUB API CONFIGURATION
# ==========================================
TIKHUB_API_KEY = env('TIKHUB_API_KEY', default='')
TIKHUB_API_BASE_URL = env('TIKHUB_API_BASE_URL', default='https://api.tikhub.io')

# ==========================================
# FACEBOOK GRAPH API CONFIGURATION
# ==========================================
META_ACCESS_TOKEN = env('META_ACCESS_TOKEN', default='')
FACEBOOK_APP_ID = env('FACEBOOK_APP_ID', default='')
FACEBOOK_APP_SECRET = env('FACEBOOK_APP_SECRET', default='')
FACEBOOK_ACCESS_TOKEN = META_ACCESS_TOKEN
INSTAGRAM_ACCESS_TOKEN = META_ACCESS_TOKEN
FERNET_KEY = env('FERNET_KEY', default='')
SUPERUSER_TOKEN = env('SUPERUSER_TOKEN', default='')

# ==========================================
# TOKEN ENCRYPTION CONFIGURATION
# ==========================================
# Khóa mã hóa Fernet cho page_access_token.
# Tạo key mới: từ video_management.utils.encryption import TokenEncryption; print(TokenEncryption.generate_encryption_key())
ENCRYPTION_KEY = env('ENCRYPTION_KEY', default='')
# ==========================================
# HEYGEN API CONFIGURATION
# ==========================================
HEYGEN_API_KEY = env('HEYGEN_API_KEY', default='')
HEYGEN_AVATAR_ID = env('HEYGEN_AVATAR_ID', default='')
HEYGEN_API_URL = env('HEYGEN_API_URL', default='https://api.heygen.com/v2')
HEYGEN_WEBHOOK_URL = env('HEYGEN_WEBHOOK_URL', default='http://localhost:8000/api/heygen/webhook')
HEYGEN_TEST_MODE = env.bool('HEYGEN_TEST_MODE', default=True)

# ==========================================
# LARK BITABLE (Checklist công việc)
# ==========================================
LARK_APP_ID = env('LARK_APP_ID', default='')
LARK_APP_SECRET = env('LARK_APP_SECRET', default='')
LARK_BASE_ID = env('LARK_BASE_ID', default='')   # app_token trong URL Bitable
LARK_TABLE_ID = env('LARK_TABLE_ID', default='')
LARK_OUTSTANDING_TABLE_ID = env('LARK_OUTSTANDING_TABLE_ID', default='tbluurIuf2qDCdFr')
LARK_FIELD_ID = env('LARK_FIELD_ID', default='')  # field lưu JSON checklist

# ==========================================
# OPENAI API CONFIGURATION
# ==========================================
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
ANTHROPIC_API_KEY = env('ANTHROPIC_API_KEY', default='')
DEEPSEEK_API_KEY = env('DEEPSEEK_API_KEY', default='')

# ==========================================
# GOOGLE GEMINI API CONFIGURATION
# ==========================================
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')

# ==========================================
# ELEVENLABS API CONFIGURATION
# ==========================================
ELEVENLABS_API_KEY = env('ELEVENLABS_API_KEY', default='')


# Douyin API settings
DOUYIN_API_BASE_URL = env('DOUYIN_API_BASE_URL', default='https://api.example.com/douyin')
DOUYIN_API_KEY = env('DOUYIN_API_KEY', default='')

# RapidAPI TikTok API settings
TIKTOK_ACCESS_TOKEN = env('TIKTOK_ACCESS_TOKEN', default='')
TIKTOK_API_HOST = env('TIKTOK_API_HOST', default='tiktok-scraper7.p.rapidapi.com')

# ==========================================
# SCRAPER SETTINGS
# ==========================================

# Retry configuration
SCRAPER_MAX_RETRIES = env.int('SCRAPER_MAX_RETRIES', default=3)
SCRAPER_RETRY_DELAY = env.int('SCRAPER_RETRY_DELAY', default=2)  # seconds

# Cache TTL (Time To Live) in seconds
SEARCH_CACHE_TTL = env.int('SEARCH_CACHE_TTL', default=3600)  # 1 hour

# Proxy settings (optional, for requests through proxy)
PROXY_URL = env('PROXY_URL', default='')

# FFmpeg path for Mix Video (nếu FFmpeg không có trong PATH, đặt đường dẫn đầy đủ, ví dụ: C:/ffmpeg/bin/ffmpeg.exe)
FFMPEG_PATH = env('FFMPEG_PATH', default='')
# FFprobe path (nếu không đặt, sẽ suy từ FFMPEG_PATH; đặt riêng nếu ffprobe ở thư mục khác)
FFPROBE_PATH = env('FFPROBE_PATH', default='')

# Mix Video: tỉ lệ khung hình output (width px; height=0 thì tự tính theo width giữ tỉ lệ gốc)
MIX_VIDEO_OUTPUT_WIDTH = env.int('MIX_VIDEO_OUTPUT_WIDTH', default=720)
MIX_VIDEO_OUTPUT_HEIGHT = env.int('MIX_VIDEO_OUTPUT_HEIGHT', default=0)  # 0 = auto (scale theo width)

# Telegram settings
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_CHAT_ID = env('TELEGRAM_CHAT_ID', default='')

# Celery Beat Schedule — Facebook 3-Phase Scraper
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'cleanup-cache-daily': {
        'task': 'video_management.cleanup_old_cache',
        'schedule': 86400.0,
    },
    # GĐ0: Tự phát hiện page mới (mỗi ngày lúc 6h sáng VN = 23h UTC ngày trước)
    'facebook-auto-import-pages': {
        'task': 'video_management.auto_import_pages',
        'schedule': crontab(minute=0, hour=23),
    },
    # GĐ1: Backfill page chưa cào lịch sử (1 lần/ngày lúc 6:30 VN = 23:30 UTC)
    'facebook-backfill-new-pages': {
        'task': 'video_management.backfill_all_pages',
        'schedule': crontab(minute=30, hour=23),
    },
    # GĐ2: Delta sync bài mới (mỗi ngày lúc 7h sáng VN = 0h UTC)
    'facebook-delta-sync-daily': {
        'task': 'video_management.delta_sync_all_pages',
        'schedule': crontab(minute=0, hour=0),
    },
    # GĐ3: Refresh metrics video 7 ngày gần đây (mỗi ngày lúc 12h trưa VN = 5h UTC)
    'facebook-refresh-metrics-daily': {
        'task': 'video_management.refresh_recent_metrics',
        'schedule': crontab(minute=0, hour=5),
        'kwargs': {'days': 7},
    },
    # Scraper: Cào reels mới cho pages đánh dấu (mỗi ngày lúc 6h sáng VN = 23h UTC)
    'scraper-periodic-reels': {
        'task': 'video_management.periodic_scrape_marked_pages',
        'schedule': crontab(minute=0, hour=23),
    },
    # TikTok: Cào posts mới cho profiles theo dõi (mỗi ngày lúc 5h30 sáng VN = 22h30 UTC)
    'tiktok-periodic-profile-posts': {
        'task': 'video_management.periodic_scrape_tiktok_profiles',
        'schedule': crontab(minute=30, hour=22),
    },
    # Instagram: Cào reels mới + cập nhật metrics 7 ngày (mỗi ngày lúc 7h30 sáng VN = 0h30 UTC)
    'instagram-periodic-profile-reels': {
        'task': 'video_management.periodic_scrape_instagram_profiles',
        'schedule': crontab(minute=30, hour=0),
    },
    # Douyin: Cào video mới cho profiles theo dõi (mỗi ngày lúc 8h sáng VN = 1h UTC)
    'douyin-periodic-profile-videos': {
        'task': 'video_management.periodic_scrape_douyin_profiles',
        'schedule': crontab(minute=0, hour=1),
    },
    # Xiaohongshu: Cào video mới cho profiles theo dõi (mỗi ngày lúc 8h sáng VN = 1h UTC)
    'xhs-periodic-profile-videos': {
        'task': 'video_management.periodic_scrape_xhs_profiles',
        'schedule': crontab(minute=0, hour=1),
    },
    # Đã chuyển sang cron JS (social-sync.scheduler.js) chạy lúc 01:00 AM hàng ngày
    # 'daily-sync-traffic-ads': {
    #     'task': 'video_management.tasks.daily_sync',
    #     'schedule': 86400.0,
    #     'options': {'queue': 'default'},
    # },
    # 'crawl-social-insights-weekly': {
    #     'task': 'video_management.tasks.crawl_social_insights',
    #     'schedule': 604800.0,
    #     'options': {'queue': 'default'},
    # },
}


# ==========================================
# VIDEO PATHS CONFIGURATION
# ==========================================
# Base paths for video folders (network paths hoặc ổ đĩa local đã map)
# Ví dụ: VIDEO_BASE_PATHS=//VCB_MEDIA/MEDIA VCB folder,//192.168.1.250/MEDIA VCB folder,Z:/
VIDEO_BASE_PATHS = env.list('VIDEO_BASE_PATHS', default=[
    r'\\VCB_MEDIA\MEDIA VCB folder',
    r'\\192.168.1.250\MEDIA VCB folder',
])

# Thư mục chứa video sản phẩm (dưới mỗi base path). Hệ thống tìm folder có tên chứa mã SKU trong đây.
PRODUCT_VIDEO_SUBFOLDER = env('PRODUCT_VIDEO_SUBFOLDER', default=r'VIDEO Sản Phẩm')

# (Tùy chọn) Đường dẫn ĐẦY ĐỦ để quét tìm video sản phẩm. Nếu có → dùng thay vì VIDEO_BASE_PATHS + PRODUCT_VIDEO_SUBFOLDER.
# Ví dụ: PRODUCT_VIDEO_PATHS=//VCB_MEDIA/MEDIA VCB folder/VIDEO Sản Phẩm,Z:/VIDEO Sản Phẩm,D:/Videos/Sản phẩm
PRODUCT_VIDEO_PATHS = env.list('PRODUCT_VIDEO_PATHS', default=[])

# Manufacturing (Chế tác) folder - append dưới VIDEO_BASE_PATHS
# Ví dụ: Chế tác sản phẩm\Việt Nam → path: Generate Video\Chế tác sản phẩm\Việt Nam\<Nhẫn>\<NM101_...>
MANUFACTURING_FOLDER_PATH = env('MANUFACTURING_FOLDER_PATH', default=r'Chế tác sản phẩm\Việt Nam')

# HuyK video folder (chứa video KOC/HuyK cho Slot 2 & 4)
# Nếu để trống, hệ thống tự scan trong VIDEO_BASE_PATHS
HUYK_VIDEO_PATH = env('HUYK_VIDEO_PATH', default='')

# Outro folder (chứa video outro cho Slot 7)
# Nếu để trống, hệ thống tự scan tìm folder 'outro' hoặc 'source huyk'
OUTRO_FOLDER_PATH = env('OUTRO_FOLDER_PATH', default='')


# Reload triggered
