"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=(str, ''),
    ALLOWED_HOSTS=(list, []),
)

# Read .env file if it exists
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-)wz0wv9mj6oxld#%n4gm5x!cdl&d3*@yrvoh7#joy59ma&fksy')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '0.0.0.0'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    
    # Internal apps
    'video_management',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database — PostgreSQL only (shared with BE service: video_production)
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# DATABASE_URL must be set in .env, e.g.:
#   DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/video_production

_db_url = env('DATABASE_URL', default='')
if not _db_url:
    raise RuntimeError(
        "DATABASE_URL is not set! "
        "Add it to .env, e.g.: DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/video_production"
    )

DATABASES = {
    'default': env.db('DATABASE_URL')
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploaded content)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'video_management': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# Celery settings
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Local Memory Cache for Development (Fallback if Redis is missing)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}


# CORS settings
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=True)  # Enable for development
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://localhost:5173',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
])
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ==========================================
# APIFY CONFIGURATION (Primary Scraping Service)
# ==========================================
APIFY_API_TOKEN = env('APIFY_API_TOKEN', default='')

# Apify Actor IDs for different platforms
APIFY_ACTORS = {
    'tiktok': env('APIFY_ACTOR_TIKTOK', default='OtzYfK1ndEGdwWFKQ'),  # TikTok Scraper with full authorMeta
    'instagram': env('APIFY_ACTOR_INSTAGRAM', default='apify/instagram-scraper'),
    'instagram_reels': env('APIFY_ACTOR_INSTAGRAM_REELS', default='apify/instagram-reel-scraper'),
    'instagram_hashtag': env('APIFY_ACTOR_INSTAGRAM_HASHTAG', default='apify/instagram-hashtag-scraper'),
    'facebook': env('APIFY_ACTOR_FACEBOOK', default='apify/facebook-posts-scraper'),
    'facebook_page': env('APIFY_ACTOR_FACEBOOK_PAGE', default='apify/facebook-pages-scraper'),
    'facebook_hashtag': env('APIFY_ACTOR_FACEBOOK_HASHTAG', default='apify/facebook-hashtag-scraper'),  # For keyword/hashtag search
    'facebook_search': env('APIFY_ACTOR_FACEBOOK_SEARCH', default='powerai~facebook-post-search-scraper'),  # DEPRECATED: Returns 503
    'douyin': env('APIFY_ACTOR_DOUYIN', default=''),  # Custom actor if available
}

# Apify timeout settings (in seconds)
APIFY_TIMEOUT = env.int('APIFY_TIMEOUT', default=900)  # 15 minutes
APIFY_MAX_RESULTS = env.int('APIFY_MAX_RESULTS', default=10000)

# ==========================================
# FACEBOOK GRAPH API CONFIGURATION
# ==========================================
FACEBOOK_APP_ID = env('FACEBOOK_APP_ID', default='')
FACEBOOK_APP_SECRET = env('FACEBOOK_APP_SECRET', default='')
FACEBOOK_ACCESS_TOKEN = env('FACEBOOK_ACCESS_TOKEN', default='')

# ==========================================
# HEYGEN API CONFIGURATION
# ==========================================
HEYGEN_API_KEY = env('HEYGEN_API_KEY', default='')
HEYGEN_AVATAR_ID = env('HEYGEN_AVATAR_ID', default='')
HEYGEN_API_URL = env('HEYGEN_API_URL', default='https://api.heygen.com/v2')
HEYGEN_WEBHOOK_URL = env('HEYGEN_WEBHOOK_URL', default='http://localhost:8000/api/heygen/webhook')
HEYGEN_TEST_MODE = env.bool('HEYGEN_TEST_MODE', default=True)

# ==========================================
# LARK BITABLE (Checklist công việc)
# ==========================================
LARK_APP_ID = env('LARK_APP_ID', default='')
LARK_APP_SECRET = env('LARK_APP_SECRET', default='')
LARK_BASE_ID = env('LARK_BASE_ID', default='')   # app_token trong URL Bitable
LARK_TABLE_ID = env('LARK_TABLE_ID', default='')
LARK_FIELD_ID = env('LARK_FIELD_ID', default='')  # field lưu JSON checklist

# ==========================================
# OPENAI API CONFIGURATION
# ==========================================
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')

# ==========================================
# GOOGLE GEMINI API CONFIGURATION
# ==========================================
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')

# ==========================================
# ELEVENLABS API CONFIGURATION
# ==========================================
ELEVENLABS_API_KEY = env('ELEVENLABS_API_KEY', default='')


# Douyin API settings
DOUYIN_API_BASE_URL = env('DOUYIN_API_BASE_URL', default='https://api.example.com/douyin')
DOUYIN_API_KEY = env('DOUYIN_API_KEY', default='')

# RapidAPI TikTok API settings
TIKTOK_API_KEY = env('TIKTOK_API_KEY', default='')
TIKTOK_API_HOST = env('TIKTOK_API_HOST', default='tiktok-scraper7.p.rapidapi.com')

# ==========================================
# SCRAPER SETTINGS
# ==========================================

# Retry configuration
SCRAPER_MAX_RETRIES = env.int('SCRAPER_MAX_RETRIES', default=3)
SCRAPER_RETRY_DELAY = env.int('SCRAPER_RETRY_DELAY', default=2)  # seconds

# Cache TTL (Time To Live) in seconds
SEARCH_CACHE_TTL = env.int('SEARCH_CACHE_TTL', default=3600)  # 1 hour

# Proxy settings (optional, for requests through proxy)
PROXY_URL = env('PROXY_URL', default='')

# FFmpeg path for Mix Video (nếu FFmpeg không có trong PATH, đặt đường dẫn đầy đủ, ví dụ: C:/ffmpeg/bin/ffmpeg.exe)
FFMPEG_PATH = env('FFMPEG_PATH', default='')
# FFprobe path (nếu không đặt, sẽ suy từ FFMPEG_PATH; đặt riêng nếu ffprobe ở thư mục khác)
FFPROBE_PATH = env('FFPROBE_PATH', default='')

# Mix Video: tỉ lệ khung hình output (width px; height=0 thì tự tính theo width giữ tỉ lệ gốc)
MIX_VIDEO_OUTPUT_WIDTH = env.int('MIX_VIDEO_OUTPUT_WIDTH', default=720)
MIX_VIDEO_OUTPUT_HEIGHT = env.int('MIX_VIDEO_OUTPUT_HEIGHT', default=0)  # 0 = auto (scale theo width)

# Telegram settings
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_CHAT_ID = env('TELEGRAM_CHAT_ID', default='')

# Celery Beat Schedule
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'cleanup-cache-daily': {
        'task': 'video_management.cleanup_old_cache',
        'schedule': crontab(hour=0, minute=0),
    },
}


# ==========================================
# VIDEO PATHS CONFIGURATION
# ==========================================
# Base paths for video folders (network paths hoặc ổ đĩa local đã map)
# Ví dụ: VIDEO_BASE_PATHS=//VCB_MEDIA/MEDIA VCB folder,//192.168.1.250/MEDIA VCB folder,Z:/
VIDEO_BASE_PATHS = env.list('VIDEO_BASE_PATHS', default=[
    r'\\VCB_MEDIA\MEDIA VCB folder',
    r'\\192.168.1.250\MEDIA VCB folder',
])

# Thư mục chứa video sản phẩm (dưới mỗi base path). Hệ thống tìm folder có tên chứa mã SKU trong đây.
PRODUCT_VIDEO_SUBFOLDER = env('PRODUCT_VIDEO_SUBFOLDER', default=r'VIDEO Sản Phẩm')

# (Tùy chọn) Đường dẫn ĐẦY ĐỦ để quét tìm video sản phẩm. Nếu có → dùng thay vì VIDEO_BASE_PATHS + PRODUCT_VIDEO_SUBFOLDER.
# Ví dụ: PRODUCT_VIDEO_PATHS=//VCB_MEDIA/MEDIA VCB folder/VIDEO Sản Phẩm,Z:/VIDEO Sản Phẩm,D:/Videos/Sản phẩm
PRODUCT_VIDEO_PATHS = env.list('PRODUCT_VIDEO_PATHS', default=[])

# Manufacturing (Chế tác) folder location - append dưới VIDEO_BASE_PATHS
MANUFACTURING_FOLDER_PATH = env('MANUFACTURING_FOLDER_PATH', default=r'CHẾ TÁC SẢN PHẨM (xưởng)\Việt Nam')


# Reload triggered
