# Generated by Django 6.0.1 on 2026-01-26 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], db_index=True, help_text='Social media platform', max_length=20)),
                ('keyword', models.CharField(db_index=True, help_text='Search keyword or hashtag', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cached', 'Cached')], db_index=True, default='pending', max_length=20)),
                ('min_likes', models.IntegerField(default=0, help_text='Minimum likes filter', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_views', models.IntegerField(default=0, help_text='Minimum views filter', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_results', models.IntegerField(default=20, help_text='Maximum number of results', validators=[django.core.validators.MinValueValidator(1)])),
                ('results_count', models.IntegerField(default=0, help_text='Number of results found')),
                ('raw_results', models.JSONField(blank=True, default=list, help_text='Raw API response data')),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for async operations', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if search failed', null=True)),
                ('execution_time', models.FloatField(default=0.0, help_text='Execution time in seconds')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cache entry expires')),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'keyword', '-created_at'], name='video_manag_platfor_cf643f_idx'), models.Index(fields=['status', '-created_at'], name='video_manag_status_b42a65_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], db_index=True, max_length=20)),
                ('channel_id', models.CharField(help_text='Platform-specific channel/user ID', max_length=255)),
                ('username', models.CharField(db_index=True, help_text='Channel username', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Channel display name', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether to actively track this channel')),
                ('check_interval_minutes', models.IntegerField(default=60, help_text='How often to check for new content (minutes)', validators=[django.core.validators.MinValueValidator(5)])),
                ('min_likes_threshold', models.IntegerField(default=1000, help_text='Only track videos with at least this many likes', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time this channel was checked', null=True)),
                ('follower_count', models.BigIntegerField(default=0, help_text='Number of followers/subscribers')),
            ],
            options={
                'verbose_name': 'Tracked Channel',
                'verbose_name_plural': 'Tracked Channels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='video_manag_platfor_25d894_idx'), models.Index(fields=['is_active', 'last_checked_at'], name='video_manag_is_acti_28ee72_idx')],
                'unique_together': {('platform', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='ScrapedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], db_index=True, max_length=20)),
                ('video_id', models.CharField(db_index=True, help_text='Platform-specific video ID', max_length=255, unique=True)),
                ('title', models.TextField(blank=True, help_text='Video title or caption')),
                ('description', models.TextField(blank=True, help_text='Video description')),
                ('author_username', models.CharField(db_index=True, help_text='Content creator username', max_length=255)),
                ('author_name', models.CharField(blank=True, help_text='Content creator display name', max_length=255)),
                ('likes_count', models.BigIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('views_count', models.BigIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shares_count', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('video_url', models.URLField(help_text='Direct video URL', max_length=1000)),
                ('download_url', models.URLField(blank=True, help_text='Download URL (if available)', max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail image URL', max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When video was published on platform', null=True)),
                ('hashtags', models.JSONField(blank=True, default=list, help_text='List of hashtags')),
                ('music_info', models.JSONField(blank=True, default=dict, help_text='Music/audio information')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Complete raw data from platform')),
                ('search_history', models.ForeignKey(blank=True, help_text='Search that found this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='video_management.searchhistory')),
            ],
            options={
                'verbose_name': 'Scraped Video',
                'verbose_name_plural': 'Scraped Videos',
                'ordering': ['-likes_count', '-views_count'],
                'indexes': [models.Index(fields=['platform', '-likes_count'], name='video_manag_platfor_4f25a9_idx'), models.Index(fields=['platform', '-views_count'], name='video_manag_platfor_d00e35_idx'), models.Index(fields=['author_username', '-created_at'], name='video_manag_author__e7db45_idx')],
            },
        ),
    ]
