# Generated by Django 6.0.1 on 2026-01-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about why this video was added')),
                ('order', models.IntegerField(default=0, help_text='Display order within collection')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_collections', to='video_management.scrapedvideo')),
            ],
            options={
                'verbose_name': 'Collection Video',
                'verbose_name_plural': 'Collection Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Collection name/label', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Collection description')),
                ('color', models.CharField(default='#3B82F6', help_text='Color for UI display (hex format)', max_length=7)),
                ('videos', models.ManyToManyField(help_text='Videos in this collection', related_name='collections', through='video_management.CollectionVideo', to='video_management.scrapedvideo')),
            ],
            options={
                'verbose_name': 'Video Collection',
                'verbose_name_plural': 'Video Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionvideo',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_videos', to='video_management.videocollection'),
        ),
        migrations.AddIndex(
            model_name='videocollection',
            index=models.Index(fields=['name', '-created_at'], name='video_manag_name_1e4f76_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionvideo',
            index=models.Index(fields=['collection', 'order'], name='video_manag_collect_c2bc46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionvideo',
            unique_together={('collection', 'video')},
        ),
    ]
