# Generated by Django 6.0.1 on 2026-01-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_management", "0002_collectionvideo_videocollection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedchannel",
            name="total_videos",
            field=models.IntegerField(
                default=0, help_text="Total number of videos on the channel"
            ),
        ),
    ]
