# Generated by Django 6.0.1 on 2026-01-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0003_trackedchannel_total_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedchannel',
            name='total_videos',
        ),
    ]
