# Generated by Django 6.0.1 on 2026-01-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0004_remove_trackedchannel_total_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedvideo',
            name='duration',
            field=models.FloatField(default=0, help_text='Video duration in seconds'),
        ),
        migrations.AddField(
            model_name='scrapedvideo',
            name='feature_vector',
            field=models.BinaryField(blank=True, help_text='Extracted feature vector for AI comparison', null=True),
        ),
    ]
