# Generated by Django 5.2.11 on 2026-02-05 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0005_scrapedvideo_duration_scrapedvideo_feature_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(db_index=True, help_text='Facebook page username or ID', max_length=255, unique=True)),
                ('page_name', models.CharField(blank=True, help_text='Display name of the page', max_length=255)),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture URL', max_length=1000)),
                ('followers_count', models.BigIntegerField(default=0, help_text='Number of followers', validators=[django.core.validators.MinValueValidator(0)])),
                ('likes_count', models.BigIntegerField(default=0, help_text='Number of page likes', validators=[django.core.validators.MinValueValidator(0)])),
                ('page_description', models.TextField(blank=True, help_text='Page description/bio')),
                ('page_category', models.CharField(blank=True, help_text='Page category', max_length=255)),
                ('verified', models.BooleanField(default=False, help_text='Whether page is verified')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Complete raw data from Apify')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cache entry expires (24h TTL)')),
                ('last_fetched_at', models.DateTimeField(auto_now=True, help_text='Last time data was fetched from external API')),
            ],
            options={
                'verbose_name': 'Facebook Page Cache',
                'verbose_name_plural': 'Facebook Page Caches',
                'ordering': ['-last_fetched_at'],
                'indexes': [models.Index(fields=['username', 'expires_at'], name='video_manag_usernam_5f9661_idx')],
            },
        ),
    ]
