# Generated by Django 5.2.11 on 2026-02-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0006_facebookpagecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokUserCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('followers_count', models.BigIntegerField(default=0)),
                ('likes_count', models.BigIntegerField(default=0)),
                ('videos_count', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Cache expiry 24h')),
                ('last_fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='video_manag_usernam_57fb44_idx'), models.Index(fields=['expires_at'], name='video_manag_expires_dfc7d5_idx')],
            },
        ),
    ]
