# Generated by Django 5.2.11 on 2026-02-06 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0007_tiktokusercache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedvideo',
            name='feature_vector',
            field=models.BinaryField(blank=True, help_text='[DEPRECATED] Extracted feature vector for AI comparison', null=True),
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Friendly name of the voice', max_length=255)),
                ('voice_id', models.CharField(db_index=True, help_text='Provider-specific voice ID (e.g., HeyGen ID)', max_length=255, unique=True)),
                ('provider', models.CharField(default='heygen', help_text='Voice provider (heygen, elevenlabs, etc.)', max_length=50)),
                ('is_cloned', models.BooleanField(default=False, help_text='Whether this is a cloned voice from a user')),
                ('is_system', models.BooleanField(default=False, help_text='Whether this is a default system voice')),
                ('language', models.CharField(default='vi', help_text='Language code (vi, en, etc.)', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('sample_audio_url', models.URLField(blank=True, help_text='URL to sample audio of this voice', null=True)),
                ('source_video', models.ForeignKey(blank=True, help_text='Source video this voice was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_voices', to='video_management.scrapedvideo')),
            ],
            options={
                'verbose_name': 'Voice',
                'verbose_name_plural': 'Voices',
                'ordering': ['-is_system', 'name'],
                'indexes': [models.Index(fields=['provider', 'is_system'], name='video_manag_provide_6c388c_idx')],
            },
        ),
    ]
