# Generated by Django 6.0.1 on 2026-02-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0007_tiktokusercache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.JSONField(default=dict, help_text='Khung giờ cho phép báo cáo theo ngày trong tuần')),
                ('one_report_per_day', models.BooleanField(default=True, help_text='Chỉ cho phép submit 1 báo cáo/ngày')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', help_text='Timezone để check thời gian', max_length=50)),
                ('updated_by', models.CharField(blank=True, help_text='Email của manager cập nhật settings lần cuối', max_length=255)),
            ],
            options={
                'verbose_name': 'Report Settings',
                'verbose_name_plural': 'Report Settings',
            },
        ),
        migrations.AlterField(
            model_name='scrapedvideo',
            name='feature_vector',
            field=models.BinaryField(blank=True, help_text='[DEPRECATED] Extracted feature vector for AI comparison', null=True),
        ),
    ]
