# Generated by Django 5.2.11 on 2026-02-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0008_alter_scrapedvideo_feature_vector_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('A1', 'Traffic (Viral Content)'), ('A2', 'Knowledge (Educational)'), ('A3', 'Credibility (Trust Building)'), ('A4', 'Conversion (Sales)'), ('A5', 'Combined (All Types)')], help_text='Content strategy type (A1-A5)', max_length=2)),
                ('title', models.CharField(help_text='Generated video title', max_length=500)),
                ('script', models.TextField(help_text='Full generated script/content')),
                ('hook', models.TextField(blank=True, help_text='Hook section (0-3s)')),
                ('problem', models.TextField(blank=True, help_text='Problem section')),
                ('solution', models.TextField(blank=True, help_text='Solution section')),
                ('cta', models.TextField(blank=True, help_text='Call-to-action section')),
                ('estimated_duration', models.IntegerField(default=30, help_text='Estimated video duration in seconds')),
                ('word_count', models.IntegerField(default=0, help_text='Total word count')),
                ('ai_model', models.CharField(default='gpt-4', help_text='AI model used for generation', max_length=50)),
                ('prompt_used', models.TextField(blank=True, help_text='Prompt template used')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this content is approved for use')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or edits')),
                ('source_video', models.ForeignKey(help_text='Original viral video this content is based on', on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='video_management.scrapedvideo')),
            ],
            options={
                'verbose_name': 'Generated Content',
                'verbose_name_plural': 'Generated Contents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'is_approved'], name='video_manag_content_defb53_idx'), models.Index(fields=['source_video', 'content_type'], name='video_manag_source__85a199_idx')],
            },
        ),
    ]
