# Generated by Django 5.2.11 on 2026-02-07 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0009_generatedcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the product list', max_length=255)),
                ('file_name', models.CharField(help_text='Original uploaded file name', max_length=500)),
                ('file_path', models.CharField(help_text='Path to stored file', max_length=1000)),
                ('total_products', models.IntegerField(default=0, help_text='Total number of products in this list')),
                ('description', models.TextField(blank=True, help_text='Optional description of this product list')),
            ],
            options={
                'verbose_name': 'Product List',
                'verbose_name_plural': 'Product Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Product name', max_length=500)),
                ('category', models.CharField(blank=True, help_text='Product category (e.g., Nhẫn, Dây chuyền, Vòng tay)', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price', max_digits=15, null=True)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('highlights', models.TextField(blank=True, help_text='Key features/highlights')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit / Product code', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='All columns from Excel row')),
                ('product_list', models.ForeignKey(help_text='Product list this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='video_management.productlist')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_list', 'category', 'name'],
                'indexes': [models.Index(fields=['product_list', 'category'], name='video_manag_product_43f33b_idx'), models.Index(fields=['name'], name='video_manag_name_e89b74_idx')],
            },
        ),
    ]
