# Generated by Django 5.2.11 on 2026-02-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0010_productlist_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalVideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(db_index=True, help_text='Absolute path to video file', max_length=1000, unique=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('modified_time', models.DateTimeField(db_index=True, help_text='File last modified timestamp')),
                ('duration', models.FloatField(help_text='Video duration in seconds')),
                ('has_audio', models.BooleanField(default=False, help_text='Whether video has audio stream')),
                ('width', models.IntegerField(blank=True, help_text='Video width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Video height in pixels', null=True)),
                ('folder_name', models.CharField(blank=True, db_index=True, help_text='Parent folder name for quick filtering', max_length=500)),
                ('last_accessed_at', models.DateTimeField(auto_now=True, help_text='Last time this cache entry was accessed')),
            ],
            options={
                'verbose_name': 'Local Video File Cache',
                'verbose_name_plural': 'Local Video File Caches',
                'ordering': ['-last_accessed_at'],
                'indexes': [models.Index(fields=['folder_name', 'duration'], name='video_manag_folder__109fe4_idx'), models.Index(fields=['file_path', 'modified_time'], name='video_manag_file_pa_a30ea7_idx'), models.Index(fields=['-last_accessed_at'], name='video_manag_last_ac_e1838f_idx')],
            },
        ),
    ]
