# Generated by Django 5.2.11 on 2026-02-07 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0011_add_local_video_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(db_index=True, help_text='Absolute path to video file (network or local)', max_length=1000, unique=True)),
                ('folder_type', models.CharField(db_index=True, help_text='Folder type: Sản phẩm, HuyK, Chế tác, etc.', max_length=50)),
                ('duration', models.FloatField(help_text='Video duration in seconds')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('has_audio', models.BooleanField(default=False, help_text='Whether video has audio stream')),
                ('width', models.IntegerField(blank=True, help_text='Video width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Video height in pixels', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, help_text='Last time this video was used in a mix', null=True)),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this video has been used')),
                ('modified_time', models.DateTimeField(help_text='File last modified timestamp')),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Whether file still exists and is accessible')),
            ],
            options={
                'verbose_name': 'Indexed Video',
                'verbose_name_plural': 'Indexed Videos',
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['folder_type', 'is_available', '-last_used_at'], name='video_manag_folder__45992f_idx'), models.Index(fields=['folder_type', 'duration'], name='video_manag_folder__362978_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoClipCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clip_path', models.CharField(db_index=True, help_text='Path to cached clip file', max_length=1000, unique=True)),
                ('start_time', models.FloatField(help_text='Start time in source video (seconds)')),
                ('duration', models.FloatField(help_text='Clip duration in seconds')),
                ('file_size', models.BigIntegerField(help_text='Clip file size in bytes')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this clip was accessed (LRU)')),
                ('access_count', models.IntegerField(default=0, help_text='Number of times this clip has been used')),
                ('generated_with_gpu', models.BooleanField(default=False, help_text='Whether this clip was generated with GPU acceleration')),
                ('generation_time', models.FloatField(default=0.0, help_text='Time taken to generate this clip (seconds)')),
                ('source_video', models.ForeignKey(help_text='Source video this clip was extracted from', on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='video_management.indexedvideo')),
            ],
            options={
                'verbose_name': 'Video Clip Cache',
                'verbose_name_plural': 'Video Clip Caches',
                'ordering': ['-last_accessed_at'],
                'indexes': [models.Index(fields=['source_video', '-last_accessed_at'], name='video_manag_source__089665_idx'), models.Index(fields=['-last_accessed_at'], name='video_manag_last_ac_9eef7c_idx'), models.Index(fields=['clip_path'], name='video_manag_clip_pa_566fe0_idx')],
            },
        ),
    ]
