# Generated by Django 5.2.11 on 2026-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0012_add_smart_preprocessing_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedvideo',
            name='file_path',
            field=models.CharField(db_index=True, help_text='Absolute path to video file (network or local)', max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='indexedvideo',
            unique_together={('file_path', 'folder_type')},
        ),
    ]
