# Generated by Django 6.0.1 on 2026-02-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0008_reportsettings_alter_scrapedvideo_feature_vector'),
        ('video_management', '0012_add_smart_preprocessing_models'),
    ]

    operations = [
    ]
