# Generated by Django 5.2.11 on 2026-02-09 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0014_fix_indexedvideo_unc_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(choices=[('TIKTOK', 'TikTok'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('DOUYIN', 'Douyin'), ('XIAOHONGSHU', 'Xiaohongshu')], db_index=True, max_length=20)),
                ('search_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('result_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_searched', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'db_table': 'video_management_searchquery',
                'indexes': [models.Index(fields=['query', 'platform'], name='video_manag_query_6740a3_idx'), models.Index(fields=['platform', '-search_count'], name='video_manag_platfor_764704_idx'), models.Index(fields=['platform', '-last_searched'], name='video_manag_platfor_2305f0_idx')],
                'unique_together': {('query', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='TrendingKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(choices=[('TIKTOK', 'TikTok'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('DOUYIN', 'Douyin'), ('XIAOHONGSHU', 'Xiaohongshu')], db_index=True, max_length=20)),
                ('trend_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('video_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_views', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_likes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trending Keyword',
                'verbose_name_plural': 'Trending Keywords',
                'db_table': 'video_management_trendingkeyword',
                'indexes': [models.Index(fields=['keyword', 'platform'], name='video_manag_keyword_0bc0fa_idx'), models.Index(fields=['platform', '-trend_score'], name='video_manag_platfor_26a627_idx')],
                'unique_together': {('keyword', 'platform')},
            },
        ),
    ]
