# Generated by Django 5.2.11 on 2026-02-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0015_searchquery_trendingkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='search_mode',
            field=models.CharField(blank=True, db_index=True, default='hashtag', help_text='Search mode: keyword (caption) or hashtag', max_length=20),
        ),
    ]
