# Generated by Django 6.0.1 on 2026-02-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0013_merge_20260208_1341'),
        ('video_management', '0015_searchquery_trendingkeyword'),
    ]

    operations = [
    ]
