# Generated by Django 6.0.1 on 2026-02-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0016_merge_20260210_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSettings',
        ),
    ]
