# Generated by Django 6.0.1 on 2026-03-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0016_add_search_mode_to_search_history'),
        ('video_management', '0018_appuser_larkemployee_larkpermission_larkreport_and_more'),
    ]

    operations = [
    ]
