# Generated by Django 5.2.11 on 2026-03-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0019_merge_20260302_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedvideo',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('xiaohongshu', 'Xiaohongshu')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('xiaohongshu', 'Xiaohongshu')], db_index=True, help_text='Social media platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackedchannel',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('xiaohongshu', 'Xiaohongshu')], db_index=True, max_length=20),
        ),
    ]
