# Generated by Django 6.0.1 on 2026-03-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0019_merge_20260302_1045'),
        ('video_management', '0020_alter_scrapedvideo_platform_and_more'),
    ]

    operations = [
    ]
