# Generated by Django 6.0.1 on 2026-03-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0021_merge_20260304_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.JSONField(default=dict, help_text='Khung giờ báo cáo theo ngày (monday, tuesday, ...)')),
                ('one_report_per_day', models.BooleanField(default=True, help_text='Chỉ cho phép submit 1 báo cáo/ngày')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50)),
                ('is_random', models.BooleanField(default=False, help_text='Bật chế độ báo cáo ngẫu nhiên')),
                ('random_minutes', models.IntegerField(default=30, help_text='Số phút báo cáo ngẫu nhiên trong khung giờ')),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Report Settings',
                'verbose_name_plural': 'Report Settings',
            },
        ),
    ]
