# Generated by Django 5.2.11 on 2026-03-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0023_remove_larkemployee_extend_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('xiaohongshu', 'Xiaohongshu')], db_index=True, max_length=20)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('max_posts', models.IntegerField(default=30)),
                ('insights', models.JSONField(blank=True, default=dict, help_text='Stored Gemini insights JSON')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Stored metrics/charts JSON')),
            ],
            options={
                'verbose_name': 'Channel Analysis',
                'verbose_name_plural': 'Channel Analyses',
                'indexes': [models.Index(fields=['platform', 'username'], name='video_manag_platfor_426825_idx')],
                'unique_together': {('platform', 'username')},
            },
        ),
    ]
