# Generated by Django 4.2.30 on 2026-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0024_channelanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelanalysis',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('xiaohongshu', 'Xiaohongshu'), ('youtube', 'YouTube')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapedvideo',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('xiaohongshu', 'Xiaohongshu'), ('youtube', 'YouTube')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('xiaohongshu', 'Xiaohongshu'), ('youtube', 'YouTube')], db_index=True, help_text='Social media platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackedchannel',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('douyin', 'Douyin'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('xiaohongshu', 'Xiaohongshu'), ('youtube', 'YouTube')], db_index=True, max_length=20),
        ),
    ]
