# Generated by Django 5.2.15 on 2026-06-17 02:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0025_alter_channelanalysis_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_id', models.CharField(db_index=True, help_text='ID cứng của Fanpage do Facebook cấp', max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Tên hiển thị của Fanpage', max_length=255)),
                ('username', models.CharField(blank=True, help_text='Facebook Page Username (Handle dạng chữ nếu có)', max_length=255, null=True)),
                ('category', models.CharField(blank=True, help_text='Danh mục chính của Trang', max_length=255)),
                ('avatar_url', models.TextField(blank=True, help_text='URL ảnh đại diện lấy từ Facebook', null=True)),
                ('page_access_token', models.TextField(help_text='Page Access Token dài hạn (thường là vĩnh viễn trừ khi đổi pass hoặc hủy quyền)')),
                ('tasks', models.JSONField(blank=True, default=list, help_text='Danh sách các quyền cụ thể user có trên Page này (e.g., ANALYZE, CREATE_CONTENT)')),
                ('followers_count', models.BigIntegerField(default=0, help_text='Số lượng người theo dõi hiện tại', validators=[django.core.validators.MinValueValidator(0)])),
                ('likes_count', models.BigIntegerField(default=0, help_text='Số lượng lượt thích Trang hiện tại', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Bật/Tắt đồng bộ dữ liệu tự động cho Page này')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Thời điểm cuối cùng hệ thống kéo Insights/Metrics của Page này về', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Toàn bộ cục dữ liệu gốc trả về từ Graph API lúc phân quyền')),
            ],
            options={
                'verbose_name': 'Managed Facebook Page',
                'verbose_name_plural': 'Managed Facebook Pages',
                'ordering': ['-last_synced_at', 'name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='video_manag_is_acti_87fb9e_idx'), models.Index(fields=['is_active', 'last_synced_at'], name='video_manag_is_acti_a943e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnedVideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('caption', models.TextField(blank=True, help_text='Nội dung bài viết/Hashtag')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('permalink_url', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(db_index=True, default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('reach_count', models.IntegerField(default=0)),
                ('link_clicks', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('managed_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video_management.managedfacebookpage')),
            ],
            options={
                'verbose_name': 'Owned Video Content',
                'verbose_name_plural': 'Owned Video Contents',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['managed_page', '-view_count'], name='video_manag_managed_38672a_idx')],
            },
        ),
    ]
