# Generated by Django 5.2.15 on 2026-06-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management', '0026_managedfacebookpage_ownedvideocontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedfacebookpage',
            name='page_access_token',
            field=models.TextField(default='', help_text='[ENCRYPTED] Page Access Token dài hạn (mã hóa trước khi lưu DB)'),
        ),
    ]
